import catalogJson from "./config-catalog.json";

export type FieldPrimitive = string | number | boolean;
export type FieldType = "text" | "password" | "number" | "boolean" | "select" | "url" | "multiline" | "textarea";

export interface ConfigurationField {
  id: string;
  key: string;
  section: string | null;
  option: string | null;
  environmentAliases: string[];
  type: FieldType;
  defaultValue: FieldPrimitive;
  placeholder: string;
  secret: boolean;
  appliesTo: string;
  changeEffect: "request" | "restart" | "reindex";
  validation: string;
  minimum?: number;
  maximum?: number;
  choices?: string[];
  help: string;
}

export interface ConfigurationGroup {
  id: string;
  title: string;
  description: string;
  fields: ConfigurationField[];
}

export interface ConfigurationCatalog {
  schemaVersion: number;
  sourceOfTruth: string;
  groups: ConfigurationGroup[];
}

export type FormValues = Record<string, string>;
export type StorageTopology = "local" | "external";

// Keep the catalog in JSON so the API project can consume the exact same binding metadata.
export const configCatalog = catalogJson as unknown as ConfigurationCatalog;
export const configurationFields = configCatalog.groups.flatMap((group) => group.fields);
export const fieldsById = new Map(configurationFields.map((field) => [field.id, field]));

export function createDefaultFormValues(): FormValues {
  return Object.fromEntries(configurationFields.map((field) => [field.id, String(field.defaultValue)]));
}

export function applyStorageTopology(values: FormValues, topology: StorageTopology): FormValues {
  return topology === "local"
    ? { ...values, "document-provider": "mongo", "document-connection": "mongodb://mongo:27017", "job-provider": "mongo", "job-connection": "mongodb://mongo:27017", "vector-provider": "elasticsearch", "vector-endpoint": "http://elasticsearch:9200", "compose-profiles": "local-storage" }
    : { ...values, "document-provider": "mongo", "document-connection": "", "job-provider": "mongo", "job-connection": "", "cosmos-endpoint": "", "cosmos-key": "", "vector-provider": "elasticsearch", "vector-endpoint": "", "compose-profiles": "" };
}

export function addComposeProfile(values: FormValues, profile: "s3-emulator" | "azure-emulator", includeLocalStorage: boolean): FormValues {
  const profiles = new Set((values["compose-profiles"] ?? "").split(",").map((item) => item.trim()).filter(Boolean));
  profiles.add(profile);
  if (includeLocalStorage) profiles.add("local-storage");
  return { ...values, "compose-profiles": [...profiles].join(",") };
}

export function validateConfiguration(values: FormValues): string[] {
  const errors: string[] = [];
  for (const field of configurationFields) {
    if (field.type !== "number") continue;
    const raw = values[field.id] ?? String(field.defaultValue);
    const numeric = Number(raw);
    const minimum = field.minimum ?? (typeof field.defaultValue === "number" && Number.isInteger(field.defaultValue) ? 1 : 0);
    if (raw.trim() === "" || !Number.isFinite(numeric)) errors.push(`${field.option ?? field.key} must be a valid number.`);
    else if (typeof field.defaultValue === "number" && Number.isInteger(field.defaultValue) && !Number.isInteger(numeric)) errors.push(`${field.option ?? field.key} must be a whole number.`);
    else if (numeric < minimum) errors.push(`${field.option ?? field.key} must be at least ${minimum}.`);
    else if (field.maximum !== undefined && numeric > field.maximum) errors.push(`${field.option ?? field.key} must be no more than ${field.maximum}.`);
  }
  if (values["embedding-dimensions"] !== values["vector-dimensions"] && values["vector-provider"] === "elasticsearch") errors.push("Embedding and Elasticsearch vector dimensions must match.");
  const size = Number(values["chunk-size"]);
  const overlap = Number(values["chunk-overlap"]);
  if (Number.isFinite(size) && Number.isFinite(overlap) && overlap >= size) errors.push("Chunk overlap must be smaller than chunk size.");
  return errors;
}

function listValue(field: ConfigurationField, value: string): string[] {
  if (field.id === "allowed-roots") return value.split(/[\r\n:;]/).map((item) => item.trim()).filter(Boolean);
  return value.split(/[\r\n,]/).map((item) => item.trim()).filter(Boolean);
}

function encodeEnvValue(value: string): string {
  if (/^[\w./:@+-]*$/.test(value)) return value;
  return `'${value.replace(/'/g, "\\'")}'`;
}

function envValue(field: ConfigurationField, value: string): string {
  if (field.type === "multiline") {
    const delimiter = field.id === "allowed-roots" ? ":" : ",";
    value = listValue(field, value).join(delimiter);
  }
  return encodeEnvValue(value);
}

export function createEnvironmentFile(values: FormValues, backendUrl = "http://api:8080"): string {
  const lines = [
    "# Generated by Enterprise RAG Playground. Review it before use and keep it out of source control.",
    "# The same RAG_API_KEY is read by the API and the server-side Playground proxy.",
    `RAG_API_URL=${encodeEnvValue(backendUrl)}`,
    "",
  ];
  const usedAliases = new Set<string>(["RAG_API_URL"]);
  for (const group of configCatalog.groups) {
    const entries = group.fields.flatMap((field) => field.environmentAliases.flatMap((alias) => {
      if (usedAliases.has(alias)) return [];
      usedAliases.add(alias);
      return [[alias, field.secret ? "" : values[field.id] ?? String(field.defaultValue), field] as const];
    }));
    if (entries.length === 0) continue;
    lines.push(`# ${group.title}`);
    for (const [alias, value, field] of entries) {
      if (field.secret) lines.push(`# Secret value. Keep this file private.`);
      lines.push(`${alias}=${envValue(field, value)}`);
    }
    lines.push("");
  }
  return `${lines.join("\n")}\n`;
}

export function createAppSettings(values: FormValues): string {
  const settings: Record<string, Record<string, FieldPrimitive | string[] | null>> = {};
  for (const field of configurationFields) {
    if (!field.section || !field.option) continue;
    settings[field.section] ??= {};
    if (field.secret) {
      settings[field.section]![field.option] = null;
      continue;
    }
    const value = values[field.id] ?? String(field.defaultValue);
    if (field.type === "multiline") {
      settings[field.section]![field.option] = listValue(field, value);
    } else if (field.type === "number") {
      const numericValue = Number(value);
      settings[field.section]![field.option] = Number.isFinite(numericValue) ? numericValue : Number(field.defaultValue);
    } else if (field.type === "boolean") {
      settings[field.section]![field.option] = value === "true";
    } else {
      settings[field.section]![field.option] = value;
    }
  }
  return `${JSON.stringify(settings, null, 2)}\n`;
}

export function createSafeExampleEnvironmentFile(): string {
  const values = createDefaultFormValues();
  for (const field of configurationFields) if (field.secret) values[field.id] = "";
  return createEnvironmentFile(values);
}

export function makeDownload(name: string, contents: string, mimeType: string): void {
  const blob = new Blob([contents], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = name;
  anchor.click();
  URL.revokeObjectURL(url);
}
