import { test, expect } from "@playwright/test";
import path from "node:path";

test("client environment reports an unavailable API without demo fallback", async ({ page }) => {
    test.skip(!process.env.CLIENT_E2E, "Client mode is disabled on the public demo.");
    await page.route("**/api/client/**", route => route.fulfill({ status: 503, json: { detail: "Client API is not configured." } }));
    await page.goto("/");
    await page.getByLabel("Environment mode").selectOption("client");
    await expect(page.getByRole("alert").filter({ hasText: "Client connection" })).toContainText("not configured");
    await expect(page.getByText("Customers may request")).toHaveCount(0);
    await page.getByLabel("Environment mode").selectOption("demo");
    await expect(page.getByRole("button", { name: "Run Query" })).toBeVisible();
});

test("own data flows through ingestion, citations, retrieval, and evaluation", async ({ page }) => {
    test.skip(!process.env.CLIENT_E2E, "Requires a running client API with local source access.");
    test.setTimeout(120_000);
    const corpusName = `Browser corpus ${Date.now()}`;
    await page.goto("/integrations");
    await page.getByLabel("Environment mode").selectOption("client");
    await page.getByLabel("New corpus name").fill(corpusName);
    await page.getByRole("button", { name: "Create corpus", exact: true }).click();
    await expect(page.getByLabel("Document corpus")).toHaveValue(/.+/);
    await page.getByLabel("Document corpus").selectOption({ label: corpusName });
    await page.getByLabel("Profile name", { exact: true }).fill("Browser recursive");
    await page.getByRole("button", { name: "Create profile", exact: true }).click();
    await expect(page.getByLabel("Indexing profile")).toHaveValue(/.+/);
    await page.getByLabel("Sources, one per line").fill(process.env.CLIENT_FIXTURE_PATH ?? path.resolve("tests/fixtures/client-policy.md"));
    await page.getByRole("button", { name: "Start ingestion", exact: true }).click();
    await expect(page.getByText("ingestion · complete", { exact: false })).toBeVisible({ timeout: 30000 });
    await page.getByRole("link", { name: "Open Playground" }).click();
    await expect(page.getByRole("heading", { name: "Playground", exact: true })).toBeVisible();
    await page.getByLabel("Document corpus").selectOption({ label: corpusName });
    await page.getByLabel("Ask a question").fill("What is the refund policy?");
    await page.getByRole("slider", { name: "Minimum relevance" }).focus();
    await page.keyboard.press("Home");
    await page.getByRole("button", { name: "Run Query", exact: true }).click();
    await expect(page.getByRole("button", { name: "Citation 1: show source" })).toBeVisible({ timeout: 30000 });
    await expect(page.locator("section").filter({ has: page.getByRole("heading", { name: "Answer with source references", exact: true }) })).toContainText("30 calendar days");
    await page.getByRole("button", { name: "Citation 1: show source" }).click();
    await expect(page.locator('[data-highlighted="true"]')).toContainText("client-policy.md");
    await page.locator('[data-highlighted="true"]').getByRole("button", { name: "View document" }).click();
    await expect(page.getByRole("dialog")).toContainText("30 calendar days");
    await page.keyboard.press("Escape");
    await expect(page.getByText("measured stages", { exact: true })).toBeVisible();
    await page.evaluate(() => window.scrollTo(0, 0));
    await page.screenshot({ path: "test-results/client-playground-desktop.png", fullPage: false });
    await page.getByRole("link", { name: "Retrieval", exact: true }).first().click();
    await expect(page.getByRole("heading", { name: "Retrieval inspector", exact: true })).toBeVisible();
    await page.getByLabel("Document corpus").selectOption({ label: corpusName });
    await page.getByLabel("Ask a question").fill("enterprise refund contract");
    await page.getByRole("combobox", { name: "Retrieval mode", exact: true }).selectOption("hybrid");
    await page.getByRole("slider", { name: "Minimum relevance" }).focus();
    await page.keyboard.press("Home");
    await page.getByRole("button", { name: "Run Query", exact: true }).click();
    await expect(page.getByText("Retrieval score distribution", { exact: true })).toBeVisible({ timeout: 30000 });
    await page.getByRole("button", { name: /Inspect client-policy.md/ }).first().click();
    await expect(page.getByText("Query / chunk comparison", { exact: true })).toBeVisible();
    await page.getByRole("link", { name: "Evaluation", exact: true }).first().click();
    await expect(page.getByRole("heading", { name: "Evaluate your RAG workflow", exact: true })).toBeVisible();
    await page.getByRole("combobox", { name: "Corpus", exact: true }).selectOption({ label: corpusName });
    await page.getByRole("checkbox", { name: /Browser recursive/ }).check();
    await page.getByLabel("Evaluation dataset JSON").fill(JSON.stringify({ questions: [{ id: "refund", question: "What is the refund policy?", expectedSourceFile: "client-policy.md", goldAnchors: [{ phrase: "Refunds are available within 30 calendar days" }], expectedAnswer: "Refunds are available within 30 calendar days.", expectedAbstention: false }] }));
    await page.getByRole("button", { name: "Run evaluation", exact: true }).click();
    await expect(page.getByText("Client results · complete", { exact: true })).toBeVisible({ timeout: 30000 });
    await page.screenshot({ path: "test-results/client-evaluation-desktop.png", fullPage: true });
    await page.getByRole("button", { name: "What is the refund policy?", exact: true }).click();
    await expect(page.getByRole("dialog")).toContainText("Generated citations");
    await page.keyboard.press("Escape");
    await page.getByRole("link", { name: "Architecture", exact: true }).first().click();
    await page.getByRole("button", { name: /Citation validation/ }).click();
    await expect(page.getByRole("dialog")).toContainText("not proof of factual support");
    await page.keyboard.press("Escape");
    await page.screenshot({ path: "test-results/client-architecture-desktop.png", fullPage: true });
    await page.setViewportSize({ width: 390, height: 844 });
    await page.getByRole("button", { name: "Toggle color theme" }).click();
    await page.goto("/integrations");
    await expect(page.getByLabel("Environment mode")).toHaveValue("client");
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
    await page.screenshot({ path: "test-results/client-setup-mobile-dark.png", fullPage: true });
    await page.setViewportSize({ width: 820, height: 1180 });
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
    await page.screenshot({ path: "test-results/client-setup-tablet-dark.png", fullPage: true });
});
