"use client";
import { useState } from "react";
import { ArrowRight, Database, Network } from "lucide-react";
import { Panel, PageHeading } from "@/components/shared/panel";
import { Drawer } from "@/components/shared/drawer";
import { Badge } from "@/components/ui/badge";
import { useClientData } from "./use-client-data";
import { ClientError, ClientFooter } from "./shared";

export function LiveArchitecture() {
    const data = useClientData();
    const [selected, setSelected] = useState<string | null>(null);
    const caps = data.capabilities;
    const nodes = [
        { id: "sources", name: "Document sources", tech: "Local files · S3 · Azure Blob", detail: "Read-only mounted files or explicitly allowed cloud prefixes supply source documents. Credentials are resolved server-side.", input: "Allowed source paths", output: "Source streams and metadata" },
        { id: "parsing", name: "Parsing", tech: "Rag.Core parser adapters", detail: "Normalize supported document formats into text while retaining source identity. Source restrictions are checked before reading.", input: "Source streams", output: "Parsed documents" },
        { id: "chunking", name: "Chunking", tech: "Immutable indexing profile", detail: "Fixed, recursive, Markdown-aware, and semantic strategies produce profile-specific chunks. New settings require a new index; old query snapshots remain interpretable.", input: "Parsed documents and profile", output: "Ordered chunks with offsets" },
        { id: "embedding", name: "Embeddings", tech: caps?.embeddingModel ?? "Awaiting configuration", detail: "Calls the configured embedding provider. The configured vector dimensions must match the profile and index mapping.", input: "Chunk text or query", output: "Embedding vectors" },
        { id: "vector", name: "Vector store", tech: caps?.vectorStore ?? "Awaiting configuration", detail: "Stores profile-scoped vectors and lexical search text. Corpus and profile boundaries prevent evidence from crossing experiments.", input: "Vectors, text, profile metadata", output: "Ranked vector and lexical candidates" },
        { id: "retrieval", name: "Retrieval", tech: caps?.hybrid ? "Vector + hybrid RRF" : "Vector retrieval", detail: "Vector retrieval uses normalized cosine similarity. Hybrid mode merges lexical and vector result ranks using reciprocal-rank fusion; scores retain their separate meanings.", input: "Embedded query and retrieval settings", output: "Candidates with measured scores" },
        { id: "reranker", name: "Reranker", tech: caps?.reranker ? "Configured HTTP endpoint" : "Not configured · skipped", detail: "An optional server-configured HTTP service returns document-indexed relevance scores. Missing configuration disables the UI control; execution failures are surfaced.", input: "Question and candidate passages", output: "Reranked candidates" },
        { id: "context", name: "Context builder", tech: "Threshold + neighbors + token budget", detail: "Admits qualified candidates, optionally adds adjacent chunks, and enforces the estimated context budget. Excluded candidates retain explicit reasons.", input: "Ranked candidates", output: "Bounded context and exclusions" },
        { id: "llm", name: "Generation", tech: "Configured chat endpoint", detail: "Generates an answer from the admitted evidence. No evidence produces an insufficient-evidence response. The local deterministic provider is a smoke-test option.", input: "Question, context, configured system prompt", output: "Answer and model-emitted references" },
        { id: "citations", name: "Citation validation", tech: "Reference membership validation", detail: "Checks each generated reference against admitted chunk identifiers. A resolving reference is not proof of factual support; invalid references are visible.", input: "Answer references and context IDs", output: "Valid and invalid references" },
        { id: "response", name: "Response", tech: "Server-sent events → LiveRagGateway", detail: "Streams stage transitions and returns an immutable run containing evidence, raw scores, measured latency, and token provenance. Abort signals propagate to downstream operations.", input: "Query execution events", output: "Inspectable query result" },
    ];
    const node = nodes.find(item => item.id === selected);
    return <><PageHeading eyebrow="CLIENT PLATFORM MAP" title="Architecture" description="Your configured providers and the live ingestion, retrieval, and evaluation paths." />{data.error && <ClientError message={data.error} retry={data.refresh} />}<Panel title="Live data flow" icon={<Network size={15} />}><p className="mb-6 text-xs leading-6 text-muted-foreground">Inspect a component for its inputs, outputs, and engineering constraints. Provider labels come from the client API; connection health is reported separately in Integrations & Setup.</p><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{nodes.map((item, index) => <button key={item.id} className="relative rounded-lg border bg-muted/20 p-4 text-left hover:border-primary/50 hover:bg-accent/30" onClick={() => setSelected(item.id)}><div className="mb-3 flex justify-between"><span className="mono text-[10px] text-muted-foreground">{String(index + 1).padStart(2, "0")}</span><ArrowRight size={13} className="text-primary" /></div><h2 className="text-xs font-semibold">{item.name}</h2><p className="mt-2 text-[10px] leading-5 text-muted-foreground">{item.tech}</p></button>)}</div></Panel><div className="mt-5 grid gap-4 sm:grid-cols-3">{[["Metadata and documents", caps?.documentStore ?? "Not connected", "Persistent corpus, profile, document and evaluation records follow the selected document store."], ["Ingestion jobs", caps?.workbenchJobStore ?? caps?.jobStore ?? "Not connected", "Queued work supports progress, pause, cancellation, and resume."], ["Evaluation and observability", "Actual runs · measured stages", "Client anchor labels drive retrieval metrics. Token overlap remains a lexical proxy."]].map(([title, tech, description]) => <Panel key={title} title={title} icon={<Database size={13} />}><Badge variant="outline">{tech}</Badge><p className="mt-3 text-[11px] leading-6 text-muted-foreground">{description}</p></Panel>)}</div><Drawer open={!!node} onOpenChange={open => { if (!open) setSelected(null); }} title={node?.name ?? "Component"} description={node?.tech ?? ""}>{node && <div className="space-y-5 py-5"><p className="text-xs leading-7">{node.detail}</p><dl className="space-y-4">{[["Inputs", node.input], ["Outputs", node.output]].map(([label, value]) => <div className="rounded border p-4" key={label}><dt className="eyebrow mb-2">{label}</dt><dd className="text-xs leading-6">{value}</dd></div>)}</dl></div>}</Drawer><ClientFooter /></>;
}
